build_from:
  amd64: "ghcr.io/home-assistant/amd64-base:3.20"
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.20"
  armv7: "ghcr.io/home-assistant/armv7-base:3.20"
labels:
  org.opencontainers.image.title: "LibreLinkUp MQTT"
  org.opencontainers.image.description: "LibreLinkUp fetcher publishing to MQTT."
  org.opencontainers.image.source: "https://github.com/SpaceTeddy/ha-addon-librelinkup"